In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [2]:
df = pd.read_csv('C:/Users/reraveen/Jupyter/Dataset/mlt_retail_cust_eng_history.csv',dtype={'CUSTOMER_NO': object})

c:\users\reraveen\appdata\local\programs\python\python38\lib\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (1,71) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
df.shape

(2137142, 74)

In [4]:
#The final check we want to do is see what data types we have
df.dtypes

CUSTOMER_NO        object
HOME_BRN           object
REP_CCY           float64
CUST_AGE            int64
MARITAL_STAT       object
                   ...
PRED_CUST_LTV     float64
PRED_CUST_SEG     float64
PRED_RISK_TYPE     object
HIST_MOVE_DATE     object
PROD_RECO         float64
Length: 74, dtype: object

In [5]:
df[df.isnull().any(axis=1)]

,CUSTOMER_NO,HOME_BRN,REP_CCY,CUST_AGE,MARITAL_STAT,EMP_STAT,SPOUSE_EMP_STAT,NUM_DEPEND,CUST_INC,OVERALL_LIMIT,...,DATA_COLL_TO_DT,CHURN_STAT_DT,CHURN_STAT,PRED_CHURN_STAT,PRED_CHURN_PROB,PRED_CUST_LTV,PRED_CUST_SEG,PRED_RISK_TYPE,HIST_MOVE_DATE,PROD_RECO
0,000000418,0,NaN,44,M,F,O,1,375.0,NaN,...,14-JAN-19,14-JAN-19,0,0.0,0.0,11.26,4.0,NO RISK,21-NOV-19,NaN
1,000000422,0,NaN,39,M,F,NaN,2,506.0,NaN,...,14-JAN-19,14-JAN-19,0,0.0,0.0,169.22,6.0,NO RISK,21-NOV-19,NaN
2,000000430,0,NaN,30,S,F,NaN,0,0.0,NaN,...,14-JAN-19,14-JAN-19,0,0.0,0.0,297.39,6.0,NO RISK,21-NOV-19,NaN
3,000000433,0,NaN,77,M,U,NaN,0,0.0,NaN,...,14-JAN-19,14-JAN-19,1,1.0,1.0,NaN,6.0,HIGH,21-NOV-19,NaN
4,000000437,0,NaN,37,M,F,F,3,495.5,NaN,...,14-JAN-19,14-JAN-19,0,0.0,0.0,0.00,6.0,NO RISK,21-NOV-19,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2137137,133146421,133,NaN,37,M,S,NaN,3,0.0,NaN,...,31-DEC-17,31-MAR-18,0,NaN,NaN,NaN,NaN,NaN,16-APR-20,NaN
2137138,091166504,91,NaN,34,S,F,NaN,1,200.0,NaN,...,31-DEC-17,31-MAR-18,0,NaN,NaN,NaN,NaN,NaN,16-APR-20,NaN
2137139,201166506,201,NaN,39,M,F,NaN,3,304.0,NaN,...,31-DEC-17,31-MAR-18,0,NaN,NaN,NaN,NaN,NaN,16-APR-20,NaN
2137140,000146441,0,NaN,22,S,F,O,0,145.0,NaN,...,31-DEC-17,31-MAR-18,0,NaN,NaN,NaN,NaN,NaN,16-APR-20,NaN
2137141,141166630,141,NaN,52,M,S,NaN,9,0.0,NaN,...,31-DEC-17,31-MAR-18,0,NaN,NaN,NaN,NaN,NaN,16-APR-20,NaN

In [6]:
print(df['REP_CCY'].isnull().sum()) #since the number of NaN values equal to the Row Size we are removing the column

2137142

In [7]:
print(df['SPOUSE_EMP_STAT'].isnull().sum())

1967401

In [8]:
print(df['OVERALL_LIMIT'].isnull().sum())#since the number of NaN values equal to the Row Size we are removing the column

2137142

In [9]:

print(df['PRED_CHURN_STAT'].isnull().sum())#

1386551

In [10]:
#need to replace

In [11]:


print(df['PRED_CUST_LTV'].isnull().sum())#since the number of NaN values equal to the Row Size we are removing the column

1407325

In [12]:
#need to replace

In [13]:

print(df['PRED_CUST_SEG'].isnull().sum())#since the number of NaN values equal to the Row Size we are removing the column

1386551

In [14]:
#need to replace
#from sklearn.impute import SimpleImputer
df.fillna(0, inplace=True)
df

,CUSTOMER_NO,HOME_BRN,REP_CCY,CUST_AGE,MARITAL_STAT,EMP_STAT,SPOUSE_EMP_STAT,NUM_DEPEND,CUST_INC,OVERALL_LIMIT,...,DATA_COLL_TO_DT,CHURN_STAT_DT,CHURN_STAT,PRED_CHURN_STAT,PRED_CHURN_PROB,PRED_CUST_LTV,PRED_CUST_SEG,PRED_RISK_TYPE,HIST_MOVE_DATE,PROD_RECO
0,000000418,0,0.0,44,M,F,O,1,375.0,0.0,...,14-JAN-19,14-JAN-19,0,0.0,0.0,11.26,4.0,NO RISK,21-NOV-19,0.0
1,000000422,0,0.0,39,M,F,0,2,506.0,0.0,...,14-JAN-19,14-JAN-19,0,0.0,0.0,169.22,6.0,NO RISK,21-NOV-19,0.0
2,000000430,0,0.0,30,S,F,0,0,0.0,0.0,...,14-JAN-19,14-JAN-19,0,0.0,0.0,297.39,6.0,NO RISK,21-NOV-19,0.0
3,000000433,0,0.0,77,M,U,0,0,0.0,0.0,...,14-JAN-19,14-JAN-19,1,1.0,1.0,0.00,6.0,HIGH,21-NOV-19,0.0
4,000000437,0,0.0,37,M,F,F,3,495.5,0.0,...,14-JAN-19,14-JAN-19,0,0.0,0.0,0.00,6.0,NO RISK,21-NOV-19,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2137137,133146421,133,0.0,37,M,S,0,3,0.0,0.0,...,31-DEC-17,31-MAR-18,0,0.0,0.0,0.00,0.0,0,16-APR-20,0.0
2137138,091166504,91,0.0,34,S,F,0,1,200.0,0.0,...,31-DEC-17,31-MAR-18,0,0.0,0.0,0.00,0.0,0,16-APR-20,0.0
2137139,201166506,201,0.0,39,M,F,0,3,304.0,0.0,...,31-DEC-17,31-MAR-18,0,0.0,0.0,0.00,0.0,0,16-APR-20,0.0
2137140,000146441,0,0.0,22,S,F,O,0,145.0,0.0,...,31-DEC-17,31-MAR-18,0,0.0,0.0,0.00,0.0,0,16-APR-20,0.0
2137141,141166630,141,0.0,52,M,S,0,9,0.0,0.0,...,31-DEC-17,31-MAR-18,0,0.0,0.0,0.00,0.0,0,16-APR-20,0.0

In [15]:


print(df['PRED_RISK_TYPE'].isnull().sum())#since the number of NaN values equal to the Row Size we are removing the column

0

In [16]:


print(df['PRED_RISK_TYPE'].isnull().sum())#since the number of NaN values equal to the Row Size we are removing the column

0

In [17]:

print(df['PROD_RECO'].isnull().sum())#since the number of NaN values equal to the Row Size we are removing the column

0

In [18]:
#object dtype columns
obj_df = df.select_dtypes(include=['object']).copy()
obj_df.head()

,CUSTOMER_NO,HOME_BRN,MARITAL_STAT,EMP_STAT,SPOUSE_EMP_STAT,RECORD_STAT,DATA_EXT_DT,DATA_COLL_FROM_DT,DATA_COLL_TO_DT,CHURN_STAT_DT,PRED_RISK_TYPE,HIST_MOVE_DATE
0,000000418,0,M,F,O,O,15-JUL-19,14-JAN-18,14-JAN-19,14-JAN-19,NO RISK,21-NOV-19
1,000000422,0,M,F,0,O,15-JUL-19,14-JAN-18,14-JAN-19,14-JAN-19,NO RISK,21-NOV-19
2,000000430,0,S,F,0,O,15-JUL-19,14-JAN-18,14-JAN-19,14-JAN-19,NO RISK,21-NOV-19
3,000000433,0,M,U,0,O,15-JUL-19,14-JAN-18,14-JAN-19,14-JAN-19,HIGH,21-NOV-19
4,000000437,0,M,F,F,O,15-JUL-19,14-JAN-18,14-JAN-19,14-JAN-19,NO RISK,21-NOV-19

In [19]:
obj_df["HOME_BRN"].value_counts()

151    86488
31     60529
0      58316
153    53739
73     52832
       ...
RET        3
146        3
RR1        3
111        3
PR1        3
Name: HOME_BRN, Length: 141, dtype: int64

since "HOME_BRN" column contains 141 val -so we need to segment it or

In [20]:
obj_df["EMP_STAT"].value_counts()

S    1281549
F     464929
T     244161
U     132299
P       9180
O       4677
R        251
N         66
0         30
Name: EMP_STAT, dtype: int64

In [21]:
obj_df["MARITAL_STAT"].value_counts()

M    1740858
S     175009
E     168292
P      33513
D      17541
0       1420
R        509
Name: MARITAL_STAT, dtype: int64

In [22]:
obj_df["SPOUSE_EMP_STAT"].value_counts()

0    1967401
O     109637
S      36787
F      17363
U       3213
T       2590
P        138
R         13
Name: SPOUSE_EMP_STAT, dtype: int64

In [23]:
pd.get_dummies(obj_df, columns=["MARITAL_STAT", "EMP_STAT","SPOUSE_EMP_STAT","PRED_RISK_TYPE"], prefix=["MARITAL_", "drive","SPOUSE_EMP_","PRED_RISK_TYPE"]).head()

,CUSTOMER_NO,HOME_BRN,RECORD_STAT,DATA_EXT_DT,DATA_COLL_FROM_DT,DATA_COLL_TO_DT,CHURN_STAT_DT,HIST_MOVE_DATE,MARITAL__0,MARITAL__D,...,SPOUSE_EMP__R,SPOUSE_EMP__S,SPOUSE_EMP__T,SPOUSE_EMP__U,PRED_RISK_TYPE_0,PRED_RISK_TYPE_HIGH,PRED_RISK_TYPE_LOW,PRED_RISK_TYPE_MEDIUM,PRED_RISK_TYPE_NO RISK,PRED_RISK_TYPE_TRANSITION
0,000000418,0,O,15-JUL-19,14-JAN-18,14-JAN-19,14-JAN-19,21-NOV-19,0,0,...,0,0,0,0,0,0,0,0,1,0
1,000000422,0,O,15-JUL-19,14-JAN-18,14-JAN-19,14-JAN-19,21-NOV-19,0,0,...,0,0,0,0,0,0,0,0,1,0
2,000000430,0,O,15-JUL-19,14-JAN-18,14-JAN-19,14-JAN-19,21-NOV-19,0,0,...,0,0,0,0,0,0,0,0,1,0
3,000000433,0,O,15-JUL-19,14-JAN-18,14-JAN-19,14-JAN-19,21-NOV-19,0,0,...,0,0,0,0,0,1,0,0,0,0
4,000000437,0,O,15-JUL-19,14-JAN-18,14-JAN-19,14-JAN-19,21-NOV-19,0,0,...,0,0,0,0,0,0,0,0,1,0

In [24]:
obj_df["RECORD_STAT"].value_counts()

O    2126807
C      10335
Name: RECORD_STAT, dtype: int64

In [25]:
obj_df["PRED_RISK_TYPE"].value_counts()

0             1690561
NO RISK        252566
HIGH           156687
MEDIUM          28564
LOW              6419
TRANSITION       2345
Name: PRED_RISK_TYPE, dtype: int64

In [26]:
data_processed = pd.get_dummies(df, columns=["MARITAL_STAT", "EMP_STAT","SPOUSE_EMP_STAT","PRED_RISK_TYPE"], prefix=["MARITAL_", "drive","SPOUSE_EMP_","PRED_RISK_TYPE"])

In [27]:
#record status-0/1 value

In [28]:
from sklearn.preprocessing import LabelEncoder

lb_make = LabelEncoder()
data_processed["RECORD_STAT"] = lb_make.fit_transform(data_processed["RECORD_STAT"])
#obj_df[["make", "make_code"]].head(11)
data_processed

,CUSTOMER_NO,HOME_BRN,REP_CCY,CUST_AGE,NUM_DEPEND,CUST_INC,OVERALL_LIMIT,LIMIT_UTIL_PER,REL_PERIOD,ACC_OPEN_CLOS_RATIO,...,SPOUSE_EMP__R,SPOUSE_EMP__S,SPOUSE_EMP__T,SPOUSE_EMP__U,PRED_RISK_TYPE_0,PRED_RISK_TYPE_HIGH,PRED_RISK_TYPE_LOW,PRED_RISK_TYPE_MEDIUM,PRED_RISK_TYPE_NO RISK,PRED_RISK_TYPE_TRANSITION
0,000000418,0,0.0,44,1,375.0,0.0,0.0,1371,0.000,...,0,0,0,0,0,0,0,0,1,0
1,000000422,0,0.0,39,2,506.0,0.0,0.0,1371,0.500,...,0,0,0,0,0,0,0,0,1,0
2,000000430,0,0.0,30,0,0.0,0.0,0.0,1371,0.667,...,0,0,0,0,0,0,0,0,1,0
3,000000433,0,0.0,77,0,0.0,0.0,0.0,1371,0.500,...,0,0,0,0,0,1,0,0,0,0
4,000000437,0,0.0,37,3,495.5,0.0,0.0,1371,0.333,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2137137,133146421,133,0.0,37,3,0.0,0.0,0.0,16,0.000,...,0,0,0,0,1,0,0,0,0,0
2137138,091166504,91,0.0,34,1,200.0,0.0,0.0,16,0.000,...,0,0,0,0,1,0,0,0,0,0
2137139,201166506,201,0.0,39,3,304.0,0.0,0.0,16,0.000,...,0,0,0,0,1,0,0,0,0,0
2137140,000146441,0,0.0,22,0,145.0,0.0,0.0,16,0.000,...,0,0,0,0,1,0,0,0,0,0
2137141,141166630,141,0.0,52,9,0.0,0.0,0.0,13,0.000,...,0,0,0,0,1,0,0,0,0,0

In [29]:
#Disply the result
data_processed

,CUSTOMER_NO,HOME_BRN,REP_CCY,CUST_AGE,NUM_DEPEND,CUST_INC,OVERALL_LIMIT,LIMIT_UTIL_PER,REL_PERIOD,ACC_OPEN_CLOS_RATIO,...,SPOUSE_EMP__R,SPOUSE_EMP__S,SPOUSE_EMP__T,SPOUSE_EMP__U,PRED_RISK_TYPE_0,PRED_RISK_TYPE_HIGH,PRED_RISK_TYPE_LOW,PRED_RISK_TYPE_MEDIUM,PRED_RISK_TYPE_NO RISK,PRED_RISK_TYPE_TRANSITION
0,000000418,0,0.0,44,1,375.0,0.0,0.0,1371,0.000,...,0,0,0,0,0,0,0,0,1,0
1,000000422,0,0.0,39,2,506.0,0.0,0.0,1371,0.500,...,0,0,0,0,0,0,0,0,1,0
2,000000430,0,0.0,30,0,0.0,0.0,0.0,1371,0.667,...,0,0,0,0,0,0,0,0,1,0
3,000000433,0,0.0,77,0,0.0,0.0,0.0,1371,0.500,...,0,0,0,0,0,1,0,0,0,0
4,000000437,0,0.0,37,3,495.5,0.0,0.0,1371,0.333,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2137137,133146421,133,0.0,37,3,0.0,0.0,0.0,16,0.000,...,0,0,0,0,1,0,0,0,0,0
2137138,091166504,91,0.0,34,1,200.0,0.0,0.0,16,0.000,...,0,0,0,0,1,0,0,0,0,0
2137139,201166506,201,0.0,39,3,304.0,0.0,0.0,16,0.000,...,0,0,0,0,1,0,0,0,0,0
2137140,000146441,0,0.0,22,0,145.0,0.0,0.0,16,0.000,...,0,0,0,0,1,0,0,0,0,0
2137141,141166630,141,0.0,52,9,0.0,0.0,0.0,13,0.000,...,0,0,0,0,1,0,0,0,0,0

In [30]:
data_processed.shape

(2137142, 100)

In [31]:
# pandas drop columns using list of column names
data_processed= data_processed.drop(['DATA_EXT_DT', 'DATA_COLL_FROM_DT', 'DATA_COLL_TO_DT','CHURN_STAT_DT','HIST_MOVE_DATE'], axis=1)

In [32]:
data_processed1=data_processed.drop(['CUSTOMER_NO','HOME_BRN'],axis=1)

In [33]:
data_processed1

,REP_CCY,CUST_AGE,NUM_DEPEND,CUST_INC,OVERALL_LIMIT,LIMIT_UTIL_PER,REL_PERIOD,ACC_OPEN_CLOS_RATIO,LN_DP_AMT_RATIO,LN_DP_AC_RATIO,...,SPOUSE_EMP__R,SPOUSE_EMP__S,SPOUSE_EMP__T,SPOUSE_EMP__U,PRED_RISK_TYPE_0,PRED_RISK_TYPE_HIGH,PRED_RISK_TYPE_LOW,PRED_RISK_TYPE_MEDIUM,PRED_RISK_TYPE_NO RISK,PRED_RISK_TYPE_TRANSITION
0,0.0,44,1,375.0,0.0,0.0,1371,0.000,0.0,2.00,...,0,0,0,0,0,0,0,0,1,0
1,0.0,39,2,506.0,0.0,0.0,1371,0.500,0.0,2.00,...,0,0,0,0,0,0,0,0,1,0
2,0.0,30,0,0.0,0.0,0.0,1371,0.667,0.0,1.00,...,0,0,0,0,0,0,0,0,1,0
3,0.0,77,0,0.0,0.0,0.0,1371,0.500,0.0,0.00,...,0,0,0,0,0,1,0,0,0,0
4,0.0,37,3,495.5,0.0,0.0,1371,0.333,0.0,1.33,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2137137,0.0,37,3,0.0,0.0,0.0,16,0.000,0.0,0.00,...,0,0,0,0,1,0,0,0,0,0
2137138,0.0,34,1,200.0,0.0,0.0,16,0.000,0.0,0.00,...,0,0,0,0,1,0,0,0,0,0
2137139,0.0,39,3,304.0,0.0,0.0,16,0.000,0.0,0.00,...,0,0,0,0,1,0,0,0,0,0
2137140,0.0,22,0,145.0,0.0,0.0,16,0.000,0.0,0.00,...,0,0,0,0,1,0,0,0,0,0
2137141,0.0,52,9,0.0,0.0,0.0,13,0.000,0.0,0.00,...,0,0,0,0,1,0,0,0,0,0

In [ ]:
from sklearn.neighbors import NearestNeighbors
import numpy as np
#X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
X=np.array(data_processed1)
nbrs = NearestNeighbors(n_neighbors=4, algorithm='auto').fit(X)
distances, indices = nbrs.kneighbors(X)
indices

In [ ]:
from sklearn.neighbors import KDTree
import numpy as np
X=np.array(data_processed1)
kdt = KDTree(X, leaf_size=50, metric='euclidean')
kdt.query(X, k=2, return_distance=True)

In [ ]:

sklearn.metrics.pairwise.pairwise_distances
pairwise_distances(X, Y=None, metric='euclidean', n_jobs=1, **kwds)

In [37]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters = 10, random_state = 0)
clusters = kmeans.fit_predict(data_processed1)
kmeans.cluster_centers_

array([[ 0.00000000e+00,  4.22740091e+01,  2.46382466e+00,
         2.09301033e+02,  0.00000000e+00,  0.00000000e+00,
         7.47349086e+02,  8.55476480e-03,  6.65122262e-06,
         1.06134173e-03,  6.89943116e-03,  5.96943777e+02,
         1.02372694e-03,  1.35490641e-02,  7.61140444e-01,
         6.78058654e-01,  6.96831612e-01,  6.20095372e-01,
        -3.51647498e+01, -1.13377716e+00,  3.29268493e+00,
        -4.63412368e+01,  6.75404878e-01,  3.40567269e+00,
         6.87979225e+01,  2.86954358e-02,  3.44439696e+00,
        -4.95424264e+01, -1.47443274e+00,  2.93529728e+00,
         2.92233966e-03, -2.41113330e-02,  1.93469443e-01,
        -8.32128401e-01,  3.69763400e-02,  1.88558859e-01,
         3.57861108e-01,  9.57580436e-02,  2.30666287e-01,
        -7.29881585e-03, -4.06200543e-02,  2.29448312e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.25217393e+02,  9.95124795e-01,  1.80000000e+02,
         2.49215179e-01,  7.61352717e-02,  1.21742145e-01,
        -1.52662934e+03,  2.13067058e+00,  0.00000000e+00,
         6.69839441e-04,  8.22204328e-03,  7.86867939e-02,
         8.14159651e-01,  1.56732995e-02,  2.37745830e-04,
         8.23506270e-02,  1.41515375e-05,  2.18834659e-01,
         3.11333825e-05,  2.20622470e-03,  4.31999268e-03,
         1.18401197e-04,  5.98251530e-01,  1.14103375e-01,
         6.21205324e-02,  9.20122118e-01,  8.17675836e-03,
         5.16092421e-02,  6.50970725e-05,  6.13233291e-06,
         1.72912919e-02,  1.21561707e-03,  1.51374279e-03,
         7.97466969e-01,  7.13629016e-02,  2.83927014e-03,
         1.31500804e-02,  1.14101960e-01,  1.07881887e-03],
       [ 0.00000000e+00,  3.90442478e+01,  2.62168142e+00,
         2.24402655e+01,  0.00000000e+00,  0.00000000e+00,
         1.59953540e+02,  5.85174779e-01, -5.25160427e-20,
         1.40929204e-02,  6.06039823e-01,  1.85330570e+07,
         5.53097345e-04, -3.46944695e-18,  7.07964602e-01,
         7.85398230e-01,  8.11946903e-01,  9.04867257e-01,
         1.55218053e+02,  3.14847345e+00,  1.57079646e+00,
         4.12720354e+01,  2.26382743e+00,  1.76548673e+00,
         7.28392035e+01,  1.18893805e+00,  1.86725664e+00,
         1.04086925e+02,  7.69070796e-01,  1.73893805e+00,
         6.05486726e-01,  2.96460177e-01,  1.10619469e-02,
        -6.10973451e-01, -3.38495575e-01,  8.32667268e-16,
         7.42079646e-01,  8.18584071e-02,  5.30973451e-02,
        -4.40066372e-01,  1.12831858e-01,  1.32743363e-02,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         8.51814159e+01,  1.00000000e+00,  1.80000000e+02,
         1.26106195e-01,  1.26106195e-01,  1.26106195e-01,
        -3.34692996e+03,  7.00000000e+00,  0.00000000e+00,
        -7.48099499e-18,  2.21238938e-03,  3.98230088e-02,
         9.24778761e-01,  1.32743363e-02,  1.59919820e-18,
         1.99115044e-02,  5.42101086e-20,  8.40707965e-02,
         1.28749008e-19, -1.60461922e-17, -1.04083409e-17,
        -3.93023288e-19,  7.87610619e-01,  1.03982301e-01,
         2.43362832e-02,  9.86725664e-01,  4.16333634e-17,
         1.32743363e-02, -6.77626358e-19,  4.65868121e-20,
        -8.67361738e-17, -1.04083409e-17,  7.37257477e-18,
         5.32907052e-15,  2.16814159e-01,  8.84955752e-03,
         3.09734513e-02,  7.41150442e-01,  2.21238938e-03],
       [ 0.00000000e+00,  4.14078315e+01,  2.82276162e+00,
         1.12786810e+01,  0.00000000e+00,  0.00000000e+00,
         5.36902450e+02,  3.72864209e-01, -2.43945489e-19,
         1.28119991e-02,  3.54197390e-01,  3.87690472e+06,
         7.90016029e-04,  1.28543010e-15,  8.77719258e-01,
         8.33066178e-01,  8.25967483e-01,  7.61163270e-01,
         1.52163201e+01,  3.80968628e-01,  2.03755439e+00,
        -2.72166178e+01, -4.82706664e-01,  2.00320586e+00,
         5.43782917e-02,  5.14971376e-01,  1.93748569e+00,
         1.14194894e+01, -2.89271353e+00,  1.55553011e+00,
         5.34920998e-03,  2.06091138e-03,  2.28990153e-04,
         1.60293107e-02,  4.57980307e-04,  2.28990153e-04,
        -4.78360430e-03,  3.69361117e-03,  2.97687199e-03,
        -1.81154110e-02, -1.03343256e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.11823449e+02,  1.00000000e+00,  1.80000000e+02,
         2.08152049e-01,  2.08152049e-01,  2.08152049e-01,
        -1.15624953e+04,  6.00000000e+00,  0.00000000e+00,
        -3.56702515e-17,  6.86970460e-03,  8.03755439e-02,
         8.68330662e-01,  1.85482024e-02,  2.28990153e-04,
         2.56468972e-02, -1.46367293e-18,  5.38126861e-02,
        -2.98155597e-19, -5.63785130e-18,  1.60293107e-03,
        -4.74338450e-19,  7.72154797e-01,  1.37623082e-01,
         3.48065033e-02,  9.77329975e-01,  1.60293107e-03,
         1.46553698e-02, -6.13929480e-18,  4.23516474e-19,
         5.49576368e-03,  6.86970460e-04,  2.28990153e-04,
        -2.57571742e-14,  3.06846806e-01,  2.72498283e-02,
         3.93863064e-02,  6.23311198e-01,  3.20586215e-03],
       [ 0.00000000e+00,  4.01978114e+01,  2.77104377e+00,
         1.84393939e+01,  0.00000000e+00,  0.00000000e+00,
         2.72243266e+02,  5.16261785e-01, -7.03037346e-20,
         3.14814815e-03,  5.29377104e-01,  1.15216244e+07,
         6.14478114e-04, -3.46944695e-18,  7.79461279e-01,
         7.89562290e-01,  8.46801347e-01,  8.52693603e-01,
         1.82591170e+02,  2.77534512e+00,  1.75084175e+00,
        -1.15352618e+02,  5.95816498e-01,  1.84848485e+00,
         2.03839394e+01,  1.85170875e+00,  1.97643098e+00,
         5.50878367e+01, -8.81422559e-01,  1.69696970e+00,
        -6.69444444e-02,  2.03198653e-02,  1.01010101e-02,
        -1.90159933e-01, -1.21212121e-01, -4.55191440e-15,
         4.12626263e-02,  2.77777778e-02,  8.41750842e-04,
        -4.12626263e-02, -2.77777778e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         9.11725589e+01,  1.00000000e+00,  1.80000000e+02,
         1.43097643e-01,  1.43097643e-01,  1.43097643e-01,
        -5.33970971e+03,  6.73989899e+00,  0.00000000e+00,
         9.32413868e-18,  5.89225589e-03,  5.89225589e-02,
         8.94781145e-01,  6.73400673e-03, -1.13841228e-18,
         3.36700337e-02,  1.79570985e-19,  7.23905724e-02,
        -8.06375366e-19,  2.12503626e-17, -1.04083409e-17,
        -4.47233396e-19,  7.91245791e-01,  1.10269360e-01,
         2.60942761e-02,  9.83164983e-01,  8.41750842e-04,
         1.26262626e-02,  8.26704157e-19, -1.29596041e-19,
         3.36700337e-03,  2.14672030e-17,  2.79724161e-17,
        -8.54871729e-15,  2.18013468e-01,  3.19865320e-02,
         2.44107744e-02,  7.18013468e-01,  7.57575758e-03],
       [ 0.00000000e+00,  3.91666667e+01,  2.48333333e+00,
         3.11333333e+01,  0.00000000e+00,  0.00000000e+00,
         8.10833333e+01,  6.83333333e-01,  5.92923063e-21,
        -2.16840434e-19,  7.31666667e-01,  4.20457317e+07,
         1.30104261e-18, -3.46944695e-18,  4.66666667e-01,
         5.66666667e-01,  8.33333333e-01,  9.50000000e-01,
        -3.16784000e+02,  2.12200000e+00,  1.11666667e+00,
         2.94703500e+02,  5.00433333e+00,  1.13333333e+00,
         5.98567667e+02,  3.01800000e+00,  1.85000000e+00,
         5.91024167e+02,  6.55150000e+00,  1.76666667e+00,
        -4.33680869e-19, -1.73472348e-17,  2.22044605e-16,
         2.22044605e-16,  0.00000000e+00,  5.55111512e-17,
        -3.33066907e-16,  2.77555756e-17,  8.32667268e-17,
         8.67361738e-18,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         8.16000000e+01,  1.00000000e+00,  1.80000000e+02,
         1.00000000e-01,  1.00000000e-01,  1.00000000e-01,
        -4.93492400e+03,  7.00000000e+00,  0.00000000e+00,
         4.33680869e-19, -3.46944695e-18,  6.66666667e-02,
         8.83333333e-01,  1.66666667e-02,  2.43945489e-19,
         3.33333333e-02,  1.18584613e-20,  1.16666667e-01,
         6.77626358e-21,  1.73472348e-18, -4.33680869e-18,
         1.35525272e-19,  7.50000000e-01,  8.33333333e-02,
         5.00000000e-02,  1.00000000e+00,  6.93889390e-18,
         4.16333634e-17,  6.77626358e-20, -7.62329653e-21,
         3.46944695e-18,  0.00000000e+00, -8.67361738e-19,
         9.99200722e-16,  1.83333333e-01, -3.46944695e-18,
         3.33333333e-02,  7.83333333e-01, -4.33680869e-19],
       [ 0.00000000e+00,  4.03870334e+01,  2.80628684e+00,
         1.27131631e+01,  0.00000000e+00,  0.00000000e+00,
         3.82260118e+02,  4.50320236e-01,  2.64274280e-19,
         1.23850688e-02,  4.54055010e-01,  7.02106430e+06,
         3.35952849e-03,  9.40220124e-16,  8.19646365e-01,
         8.27111984e-01,  8.51473477e-01,  8.13752456e-01,
         6.87864008e+01,  2.12616110e+00,  1.86365422e+00,
        -3.60503536e+01, -2.41477407e-01,  1.92298625e+00,
        -7.17953635e+00,  1.73094695e+00,  1.96738703e+00,
         1.09145933e+01, -1.28433792e+00,  1.62711198e+00,
         8.89045781e-17, -1.49533164e-15,  7.77156117e-16,
        -2.28705943e-14,  1.04777298e-15, -8.71525074e-15,
         3.10609037e-02,  4.32220039e-03,  3.53634578e-03,
         3.95284872e-03,  3.14341847e-04,  5.50098232e-03,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         9.77948919e+01,  1.00000000e+00,  1.80000000e+02,
         1.65422397e-01,  1.65422397e-01,  1.65422397e-01,
        -7.82774862e+03,  6.07190570e+00,  0.00000000e+00,
         2.68882139e-17,  5.10805501e-03,  6.36542240e-02,
         8.91552063e-01,  1.41453831e-02, -1.40404181e-17,
         2.55402750e-02, -2.11758237e-19,  5.54027505e-02,
        -1.17906986e-18,  1.07986536e-16,  7.85854617e-04,
        -4.74338450e-19,  7.65422397e-01,  1.44597250e-01,
         3.37917485e-02,  9.76031434e-01,  1.17878193e-03,
         1.49312377e-02, -1.93801138e-18, -2.47333621e-19,
         7.07269155e-03,  7.85854617e-04, -7.13405029e-17,
        -2.10942375e-14,  2.52259332e-01,  2.98624754e-02,
         3.22200393e-02,  6.81728880e-01,  3.92927308e-03],
       [ 0.00000000e+00,  3.96576087e+01,  2.74456522e+00,
         2.73150543e+01,  0.00000000e+00,  0.00000000e+00,
         1.22864130e+02,  6.05978261e-01, -3.38813179e-21,
         2.71739130e-02,  6.64456522e-01,  2.68337375e+07,
         2.60208521e-18, -1.73472348e-18,  6.30434783e-01,
         7.28260870e-01,  9.29347826e-01,  8.80434783e-01,
         2.14787663e+02,  5.21853261e+00,  1.61956522e+00,
         1.99361413e+01,  1.33353261e+00,  1.76630435e+00,
         2.89281902e+02,  3.30320652e+00,  2.13043478e+00,
        -1.00416793e+02,  5.27608696e-01,  1.70652174e+00,
         1.08420217e-17,  9.36750677e-17,  6.10622664e-16,
        -2.66453526e-15, -1.73472348e-16, -6.38378239e-16,
         4.01630435e-02,  1.03260870e-01,  1.08695652e-02,
        -4.01630435e-02, -1.03260870e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         8.72010870e+01,  1.00000000e+00,  1.80000000e+02,
         1.35869565e-01,  1.35869565e-01,  1.35869565e-01,
        -1.55492663e+02,  7.00000000e+00,  0.00000000e+00,
         5.42101086e-19,  1.08695652e-02,  5.43478261e-02,
         9.13043478e-01,  5.43478261e-03,  4.33680869e-19,
         1.63043478e-02, -2.03287907e-20,  1.03260870e-01,
         0.00000000e+00,  3.90312782e-18, -8.67361738e-18,
        -2.57498016e-19,  7.44565217e-01,  1.41304348e-01,
         1.08695652e-02,  9.83695652e-01,  8.67361738e-18,
         1.08695652e-02,  1.21972744e-19, -5.08219768e-21,
        -6.59194921e-17,  5.43478261e-03,  4.11996826e-18,
        -1.44328993e-15,  2.22826087e-01,  3.26086957e-02,
         3.26086957e-02,  7.06521739e-01,  5.43478261e-03],
       [ 0.00000000e+00,  4.27115544e+01,  2.88564304e+00,
         1.30346752e+01,  0.00000000e+00,  0.00000000e+00,
         7.23080157e+02,  3.42857499e-01,  9.31736242e-19,
         2.17598860e-02,  2.62664767e-01,  1.69391310e+06,
         3.31433321e-03, -1.56819002e-15,  8.19855124e-01,
         7.85773661e-01,  7.84704904e-01,  6.81154257e-01,
        -8.12718917e+00, -8.24425840e-01,  1.96057475e+00,
        -2.63023038e+00, -1.02277045e+00,  1.90024938e+00,
         2.80019558e+01,  5.47258045e-01,  1.83802399e+00,
        -2.25398955e+01, -2.97531053e+00,  1.39258995e+00,
         4.23215770e-02, -1.11863199e-03,  4.39377746e-03,
         1.65367534e-01,  9.27680798e-03,  9.14380715e-03,
        -1.75829474e-01, -6.60254127e-03,  2.73126707e-03,
        -1.18394490e-02, -6.74860468e-03,  1.78126113e-03,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.26652535e+02,  1.00000000e+00,  1.80000000e+02,
         2.49970312e-01,  2.49970312e-01,  2.49970312e-01,
        -1.26968608e+04,  5.99952500e+00,  0.00000000e+00,
        -1.05059191e-16,  6.88754305e-03,  1.03075644e-01,
         8.47286546e-01,  1.82876143e-02,  4.75002969e-04,
         2.39876499e-02, -2.30562368e-18,  5.77128607e-02,
         4.72305571e-18, -3.42174206e-16,  1.54375965e-03,
        -4.87890978e-19,  7.72473578e-01,  1.29913312e-01,
         3.83564897e-02,  9.74112338e-01,  2.13751336e-03,
         1.24688279e-02, -4.48588649e-18,  8.85149430e-19,
         1.00938131e-02,  8.31255195e-04,  3.56252227e-04,
        -2.88657986e-14,  3.57677235e-01,  1.86438665e-02,
         4.53627835e-02,  5.75584847e-01,  2.73126707e-03],
       [ 0.00000000e+00,  4.36250000e+01,  2.87500000e+00,
         3.75000000e+01,  0.00000000e+00,  0.00000000e+00,
         1.25250000e+02,  5.41625000e-01,  8.47032947e-22,
         4.12500000e-02,  6.25000000e-01,  7.90000000e+07,
        -2.16840434e-19, -1.73472348e-18,  2.50000000e-01,
         3.75000000e-01,  7.50000000e-01,  8.75000000e-01,
        -2.57890000e+02, -2.12500000e-02,  7.50000000e-01,
         2.19890125e+03,  8.36500000e+00,  8.75000000e-01,
        -6.28936250e+02,  3.84375000e+00,  1.62500000e+00,
        -4.62598750e+02, -3.37500000e+00,  1.87500000e+00,
         0.00000000e+00,  0.00000000e+00, -2.77555756e-17,
         1.11022302e-16,  0.00000000e+00,  2.77555756e-17,
         5.55111512e-17,  1.38777878e-17,  0.00000000e+00,
         8.67361738e-19,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00375000e+02,  1.00000000e+00,  1.80000000e+02,
         1.25000000e-01,  1.25000000e-01,  1.25000000e-01,
        -2.27373675e-13,  7.00000000e+00,  0.00000000e+00,
        -1.08420217e-19,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.38777878e-17,  0.00000000e+00,  1.25000000e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.35525272e-20,  7.50000000e-01, -1.38777878e-17,
         1.25000000e-01,  1.00000000e+00, -1.73472348e-18,
         0.00000000e+00,  0.00000000e+00,  8.47032947e-22,
         3.46944695e-18,  0.00000000e+00,  2.16840434e-19,
        -1.11022302e-16,  1.25000000e-01,  4.33680869e-19,
         1.73472348e-18,  8.75000000e-01,  2.16840434e-19],
       [ 0.00000000e+00,  4.08333333e+01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         3.30000000e+02,  7.15000000e-02,  0.00000000e+00,
         2.16840434e-19,  0.00000000e+00,  0.00000000e+00,
         1.00000000e-01,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  1.11022302e-16,  2.00000000e+00,
         2.50052402e+07,  5.06666667e+01,  2.00000000e+00,
        -2.50062266e+07, -5.63333333e+01,  0.00000000e+00,
         1.42108547e-14,  0.00000000e+00,  4.44089210e-16,
         1.28350000e+04,  1.13333333e+01,  2.00000000e+00,
         4.33680869e-19,  0.00000000e+00,  0.00000000e+00,
        -1.11022302e-16,  0.00000000e+00,  2.77555756e-17,
         0.00000000e+00,  1.38777878e-17,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         7.96666667e+01,  1.00000000e+00,  1.80000000e+02,
         0.00000000e+00,  1.38777878e-17,  2.28500000e-02,
         0.00000000e+00,  1.33333333e+00,  0.00000000e+00,
         1.08420217e-19,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  4.33680869e-19,  8.67361738e-19,
         1.35525272e-20,  1.11022302e-16,  1.38777878e-17,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         6.93889390e-18,  1.35525272e-20,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  2.16840434e-19,
         3.33333333e-01,  0.00000000e+00,  4.33680869e-19,
         0.00000000e+00,  6.66666667e-01,  0.00000000e+00]])

In [39]:
print(kmeans.cluster_centers_.shape)

(10, 93)

In [35]:
scores =kmeans.score(data_processed1)

In [36]:
scores

-1.8026667021840804e+16